name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake spec

    - name: Run RuboCop
      run: bundle exec rubocop

  notify:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify status
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;
            const workflow_url = `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`;

            const message = `CI Status: ${context.job.status}
            See details at: ${workflow_url}`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: message
            });
